### ISSUE TITLE
Plugin fails to launch Prism Launcher instances

### ISSUE THREAD

**Issue by FractalGeodes** [Garulf/MC-Multi-Launcher#7]
Whenever I try to launch an instance, it just does nothing. The only thing that appears in the log when I try is this line:
```
- WARN  - JsonRPCPlugin.ExecuteAsync - Empty JSON-RPC Response.
```

**Comment by BLACK4585** [comment]
Hey, I have the same error. This begins when I enter the `mc` keyword, it shows `Value Error`.
![grafik](https://github.com/Garulf/MC-Multi-Launcher/assets/71935902/ff1472b1-6b5a-442a-abae-bc738ab293e5)

**Comment by BLACK4585** [comment]
I also found the following error in the logs:
19:20:17.4566+01:00 - FATAL - UnHandledException - 
## Exception

```
System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\FLOWLA~1\Plugins\MINECR~1.1\plugin.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\xxx\AppData\Roaming\FLOWLA~1\Plugins\MINECR~1.1\mc_launcher\__init__.py", line 3, in <module mc_launcher>
  File "C:\Users\xxx\AppData\Roaming\FLOWLA~1\Plugins\MINECR~1.1\mc_launcher\ui.py", line 15, in __init__
  File "C:\Users\xxx\AppData\Roaming\FLOWLA~1\Plugins\MINECR~1.1\mc_launcher\launcher.py", line 66, in __init__
  File "C:\Users\xxx\AppData\Roaming\FLOWLA~1\Plugins\MINECR~1.1\mc_launcher\config.py", line 5, in load
ValueError: dictionary update sequence element #0 has length 1; 2 is required

   Source: Flow.Launcher.Core
   TargetAssembly: Flow.Launcher.Core, Version=1.17.1.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Flow.Launcher.Core.dll
   TargetSite: Void MoveNext()
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 243
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 248
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 195

Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\FLOWLA~1\Plugins\MINECR~1.1\plugin.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\xxx\AppData\Roaming\FLOWLA~1\Plugins\MINECR~1.1\mc_launcher\__init__.py", line 3, in <module mc_launcher>
  File "C:\Users\xxx\AppData\Roaming\FLOWLA~1\Plugins\MINECR~1.1\mc_launcher\ui.py", line 15, in __init__
  File "C:\Users\xxx\AppData\Roaming\FLOWLA~1\Plugins\MINECR~1.1\mc_launcher\launcher.py", line 66, in __init__
  File "C:\Users\xxx\AppData\Roaming\FLOWLA~1\Plugins\MINECR~1.1\mc_launcher\config.py", line 5, in load
ValueError: dictionary update sequence element #0 has length 1; 2 is required

   Source: Flow.Launcher.Core
   TargetAssembly: Flow.Launcher.Core, Version=1.17.1.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Flow.Launcher.Core.dll
   TargetSite: Boolean <QueryForPluginAsync>b__1(Flow.Launcher.Plugin.ActionContext)
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 294
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```
